### ISSUE TITLE
Integration of Authentication & Authorization Mechanism for CRUD API with IAM (API Gateway) #2301

### ISSUE THREAD

**Issue by Schpidi** [EOEPCA/data-access#124]
only for reporting, continued in #78

**Comment by rconway** [comment]
@Schpidi For future reference...
It's not necessary to close this issue and create a duplicate for the next quarter. Instead can comment on the issue what has been done and what remains and carry over to the next WO.
In some cases it may be helpful to edit the issue title/description to align with what has been been achieved, so that it can be closed - creating additional issue(s) for the remaining work to be scheduled in the next WO. But pure 'continuation' duplicates are not helpful.
