### ISSUE TITLE
Secure secrets in develop cluster

### ISSUE THREAD

**Issue by j08lue** [EOEPCA/data-access#82]
The raster API requires a couple of secrets for access to restricted buckets.

Currently, these are included as clear text in the IAC, which is of course not sustainable.

https://github.com/EOEPCA/eoepca-plus/pull/34#issuecomment-2372293121

What options do we have? Sealed Secrets?

Perhaps look at what the minio setup does? https://github.com/EOEPCA/eoepca-plus/blob/28cd6d3e548a673047a832fc9ea602721ab30a5a/argocd/infra/minio/README.md?plain=1#L7

## Acceptance criteria

- [x] No more clear text secrets in git
- [ ] Solution works

**Comment by kalxas** [comment]
I think this still applies:
https://deployment-guide.docs.eoepca.org/current/cluster/cluster-prerequisites/#sealed-secrets

@rconway ?

**Comment by rconway** [comment]
@j08lue @kalxas 
Yes - we are still using SealedSecrets.

Typically we use a helper script to create them - for example - https://github.com/EOEPCA/eoepca-plus/blob/deploy-develop/argocd/infra/minio/ss-minio-auth.sh

This relies on having `kubeseal` installed locally.

**Comment by pantierra** [comment]
Two PRs went in. We need to check whether they work, which is not as straight forward.

**Comment by pantierra** [comment]
I redeployed. This [link](https://eoapi.develop.eoepca.org/raster/collections/sentinel-2-l2a/items/S2A_MSIL2A_20230917T100031_N0509_R122_T34UCF_20230917T143103/preview?assets=B04_10m&assets=B03_10m&assets=B02_10m&color_formula=Gamma%20RGB%203.2%20Saturation%200.8%20Sigmoidal%20RGB%2025%200.35&nodata=0) should show data, but I have the challenge that the environment variables are  filled with `map[valueFrom:map[secretKeyRef:map[key:AWS_ACCESS_KEY_ID name:data-access namespace:data-access]]]` instead of the decrypted value. Going to do debug it.

**Comment by pantierra** [comment]
It turns out:

* `envVars` is specific to eoAPI's Helm charts and is used to populate a _ConfigMap_ with variables that are then made available as environment variables to the application.
* It is not possible to read values from a secret and include them during the creation of the _ConfigMap_.
* To address this, I [modified eoAPI](https://github.com/developmentseed/eoapi-k8s/commit/100c076c7b3a2b4909ac20376bcb94337098e592) to support a new argument, `envSecrets`, which allows entire secrets to be added as environment variables.
* I deployed it an the test link (one post up) is now working correctly again.
